name: Update automated lists
on:
  push:
    branches:
        - master
    paths:
      - 'amazon.txt'
jobs:
  update:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Update categories
      run: |
        python3 convert.py categories
    - name: Commit categories
      run: |
        git add . && git commit -am "Automated categories update"
        git push
    - name: Update AdGuard list
      run: |
        python3 convert.py adguard
    - name: Commit AdGuard list
      run: |
        git add . && git commit -am "Automated AdGuard list update"
        git push
    - name: Update parsed list
      run: |
        python3 convert.py pihole
    - name: Commit parsed list
      run: |
        git add . && git commit -am "Automated parsed list update"
        git push
    - name: Update Unbound list
      run: |
        python3 convert.py unbound
    - name: Commit parsed list
      run: |
        git add . && git commit -am "Automated Unbound list update"
        git push