name: Code
on: push

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Python setup
      - uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Type check
        run: mypy
