name: Duplicate checker
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  duplicates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Python setup
      - uses: actions/setup-python@v6
        with:
          python-version-file: .python-version
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check for duplicate lines
        run: pytest tests/test_duplicates.py -v
